config {
  type: "table",
  schema: "us_taxi_trips",
  name: "stg_taxi_trips",
  description: "Staging model for taxi trips with data quality check."
}

SELECT
  src.unique_key,
  src.taxi_id,

  src.trip_start_timestamp,
  src.trip_end_timestamp,
  DATE(src.trip_start_timestamp)                    AS trip_date,
  EXTRACT(YEAR FROM src.trip_start_timestamp)       AS trip_year,
  EXTRACT(MONTH FROM src.trip_start_timestamp)      AS trip_month,
  EXTRACT(DAYOFWEEK FROM src.trip_start_timestamp)  AS trip_day_of_week,
  EXTRACT(HOUR FROM src.trip_start_timestamp)       AS trip_hour,
  src.trip_seconds                                  AS trip_seconds,
  SAFE_DIVIDE(src.trip_seconds, 3600)               AS trip_hours,
  src.trip_miles                                    AS trip_miles,

  src.pickup_census_tract,
  src.dropoff_census_tract,
  src.pickup_community_area,
  src.dropoff_community_area,

  src.fare,
  src.tips,
  src.tolls,
  src.extras,
  src.trip_total,
  src.payment_type,
  src.company,

  src.pickup_latitude,
  src.pickup_longitude,
  src.pickup_location,
  src.dropoff_latitude,
  src.dropoff_longitude,
  src.dropoff_location,

  CASE
    WHEN src.taxi_id IS NULL THEN TRUE
    WHEN src.trip_start_timestamp IS NULL THEN TRUE
    WHEN src.trip_end_timestamp IS NULL THEN TRUE
    WHEN src.trip_seconds IS NULL OR src.trip_seconds <= 0 THEN TRUE
    WHEN src.trip_miles IS NULL OR src.trip_miles < 0 THEN TRUE
    WHEN src.fare IS NULL OR src.fare < 0 THEN TRUE
    WHEN src.tips IS NULL OR src.tips < 0 THEN TRUE
    WHEN src.trip_total IS NULL OR src.trip_total < 0 THEN TRUE
    ELSE FALSE
  END AS has_data_quality_issue,
  CURRENT_TIMESTAMP() AS updated_at
FROM ${ref("taxi_trips")} AS src
