config {
  type: "table",
  schema: "us_taxi_trips",
  name: "payment_tip_behavior",
  description: "(Q4.1) Compares tipping behavior by payment type"
}

-- Finds the latest trip date (3-month window)
WITH latest_trip AS (
  SELECT
    MAX(trip_date) AS latest_trip_date
  FROM ${ref("fct_taxi_trips")}
)

-- Final build
-- Remove payment methods
SELECT
  trips.trip_date,
  trips.payment_type,
  trips.trip_date > DATE_SUB(latest_trip.latest_trip_date, INTERVAL 3 MONTH) AS is_latest_3_months,
  COUNT(*) AS trip_count,
  ROUND(SUM(trips.fare), 2) AS total_fare,
  ROUND(SUM(trips.tips), 2) AS total_tips
FROM ${ref("fct_taxi_trips")} AS trips
CROSS JOIN latest_trip
WHERE trips.payment_type IS NOT NULL
  AND trips.fare > 0
  AND trips.tips IS NOT NULL
  AND trips.payment_type NOT IN ('Dispute', 'No Charge', 'Unknown')
GROUP BY
  trips.trip_date,
  trips.payment_type,
  latest_trip.latest_trip_date
