config {
  type: "table",
  schema: "us_taxi_trips",
  name: "fct_taxi_trips",
  description: "Fact table for taxi trips."
}

SELECT
  unique_key,
  taxi_id,
  trip_start_timestamp,
  trip_end_timestamp,
  trip_date,
  trip_year,
  trip_month,
  trip_day_of_week,
  trip_hour,
  trip_seconds,
  trip_hours,
  trip_miles,
  pickup_census_tract,
  dropoff_census_tract,
  pickup_community_area,
  dropoff_community_area,
  fare,
  tips,
  tolls,
  extras,
  trip_total,
  payment_type,
  company,
  pickup_latitude,
  pickup_longitude,
  pickup_location,
  dropoff_latitude,
  dropoff_longitude,
  dropoff_location
FROM ${ref("stg_taxi_trips")}
WHERE has_data_quality_issue = FALSE
